### ISSUE TITLE
This works to testing ?

### ISSUE THREAD

**Issue by Marlysson** [tonybaloney/mocker#3]
Great work :D  , this would work just to testing behavior?

**Comment by tonybaloney** [comment]
I've followed the Docker image API specifications, so the pull feature could be used for testing, it doesn't use BRTFS sub volume mounting - yet so I've noticed the tomcat image for example doesn't work.
The project is supposed to be about learning core concepts of Docker, thinking about how they could work in Python and also, keeping it simple.
